---

#- name: install homebrew
  #shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

- name: update homebrew
  homebrew: update_homebrew=yes

- name: install taps
  homebrew_tap:
    name: '{{ item }}'
  with_items: '{{ homebrew_taps }}'

- name: install homebrew apps
  homebrew:
    name: '{{ homebrew_apps }}'
    state: latest

- name: install cask apps
  homebrew_cask:
    name: '{{ cask_apps }}'
    state: present
    sudo_password: '{{ ansible_become_pass }}'

