---

- import_playbook: containers.yml

- hosts: workstations
  tasks:
    - group_by: key={{ ansible_distribution|lower() }}_workstations
  tags:
    - always

- import_playbook: macosx-workstations.yml

- import_playbook: workstations.yml

- import_playbook: docker-hosts.yml

- import_playbook: jenkins-hosts.yml

