---

- name: uninstall old versions
  yum:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-selinux
      - docker-engine-selinux
      - docker-engine
    state: absent

- name: install docker dependencies
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: latest
    update_cache: yes

- name: add Docker CE stable repo
  command: >
    yum-config-manager --add-repo
      https://download.docker.com/linux/centos/docker-ce.repo
  #args:
    #creates: /etc/yum.repos.d/docker-ce.repo
  register: docker_ce_repo

- name: install docker-ce
  yum:
    name: docker-ce
    state: latest
    update_cache: yes
  notify: restart docker daemon

- name: create docker group
  group:
    name: docker
    state: present

- name: add user to docker group
  user:
    append: yes
    create_home: no
    groups: docker
    name: "{{ ansible_user }}"
    state: present
