---

- name: update cache and upgrade all installed packages
  yum: name='*' update_cache=yes state=latest

- name: add epel repo
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present
    update_cache: yes

- name: install common packages
  yum:
    name:
      - python
      - iputils
    state: latest

- name: install openssh-server
  yum: name=openssh-server state=latest
  when: common.configure_ssh | default('no') | bool

- name: remove python-pip package
  yum: name=python-pip state=absent

- name: install pip with get-pip.py
  include: get-pip-install.yml

# see: https://cryptography.io/en/latest/installation/#building-cryptography-on-linux
- name: install cryptography package dependencies
  yum:
    name:
      - gcc
      - libffi-devel
      - openssl-devel
      - python-devel
    state: latest
  when: common.sni_fix | default('no') | bool
  #when: ansible_python_version|version_compare('2.7.9', '<')

