---

- name: install dependencies homebrew
  homebrew:
    name: '{{ item.key }}'
    state: latest
    install_options: '{{ item.value.install_options|default(omit) }}'
    update_homebrew: yes
  with_dict:
    cmake: {}
    git: {}
    macvim: {}
    python: {}

- name: brew info macvim
  command: brew info --json=v1 macvim
  register: result

- name: set vim_installed_version fact
  set_fact:
    vim_installed_version: "{{ (result.stdout | from_json | first).linked_keg }}"

